os: linux
dist: bionic
language: python
cache:
  - directories:
    - $HOME/.cache/pip
addons:
  firefox: "latest"
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - DOCKER_BUILDKIT=1

install:
  - env
  - which python; python --version
  - make V=1 install
  - make V=1 gecko.driver
  - make V=1 node.env
  - make V=1 travis.codecov
script:
  - make V=1 themes
  - make V=1 test
after_success:
  - make V=1 test.coverage
  - codecov

stages:
  - test
  - name: docker
    if: branch = docker-buildx

jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - stage: docker
      python: "3.8"
      git:
        depth: false
      services:
        - docker
      addons: []
      before_install: true
      install: true
      script:
        - mkdir -p /etc/docker/
        - |
          echo -e '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get install -qy docker-ce
        # log into Docker HUB
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        # enable multiarch
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        # create builder for buildx
        - docker buildx create --use --name build --node build --driver-opt network=host
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make -e GIT_URL=$(git remote get-url origin) docker.push
        # build
        - make -e GIT_URL=$(git remote get-url origin) docker.push
      after_success: true

notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
