general:
    debug : False # Debug mode, only for development
    instance_name : "searx" # displayed name

search:
    safe_search : 0 # Filter results. 0: None, 1: Moderate, 2: Strict
    autocomplete : "" # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "startpage", "wikipedia" - leave blank to turn it off by default
    language : "en-US"
    engines:
      - name: arch linux wiki
      #- name: archive is
      - name: arxiv
      - name: asksteem
      - name: base
      - name: wikipedia
      - name: bing
      - name: bing images
      - name: bing news
      - name: bing videos
      #- name: bitbucket
      #- name: ccc-tv
      - name: crossref
      - name: currency
      - name: deezer
      - name: deviantart
      #- name: ddg definitions
      #- name: digbt
      - name: digg
      #- name: erowid
      - name: wikidata
      #- name: duckduckgo
      #- name: duckduckgo images
      #- name: etymonline
      #- name: faroo
      - name: 500px
      #- name: 1x
      #- name: fdroid
      #- name: findx
      #- name: findx images
      #- name: findx videos
      - name: flickr
      #- name: free software directory
      #- name: frinkiac
      - name: genius
      #- name: gigablast
      #- name: gitlab
      - name: github
      - name: google
      - name: google images
      - name: google news
      - name: google videos
      - name: google scholar
      #- name: google play apps
      #- name: google play movies
      #- name: google play music
      #- name: geektimes
      #- name: habrahabr
      - name: hoogle
      #- name: ina
      #- name: kickass
      #- name: library genesis
      - name: lobste.rs
      - name: microsoft academic
      - name: mixcloud
      #- name: nyaa
      - name: openairedatasets
      - name: openairepublications
      - name: openstreetmap
      #- name: openrepos
      - name: pdbe
      - name: photon
      - name: piratebay
      - name: pubmed
      #- name: qwant
      - name: qwant images
      - name: qwant news
      - name: qwant social
      #- name: reddit
      #- name: scanr structures
      - name: soundcloud
      - name: stackoverflow
      - name: searchcode doc
      #- name: searchcode code
      #- name: framalibre
      - name: semantic scholar
      - name: spotify
      - name: subtitleseeker
      #- name: startpage
      #- name: ixquick
      #- name: swisscows
      #- name: tokyotoshokan
      - name: torrentz
      - name: twitter
      #- name: yahoo
      #- name: yandex
      - name: yahoo news
      - name: youtube
      - name: dailymotion
      - name: vimeo
      - name: wolframalpha
      #- name: seedpeer
      - name: dictzone
      #- name: mymemory translated
      #- name: voat
      #- name: 1337x

server:
    port : 8888
    bind_address : "127.0.0.1" # address to listen on
    secret_key : "ultrasecretkey" # change this!
    base_url : False # Set custom base_url. Possible values: False or "https://your.custom.host/location/"
    image_proxy : False # Proxying image results through searx
    http_protocol_version : "1.0"  # 1.0 and 1.1 are supported

ui:
    static_path : "" # Custom static path - leave it blank if you didn't change
    templates_path : "" # Custom templates path - leave it blank if you didn't change
    default_theme : oscar # ui theme
    default_locale : "" # Default interface locale - leave blank to detect from browser information or use codes from the 'locales' config section

# searx supports result proxification using an external service: https://github.com/asciimoo/morty
# uncomment below section if you have running morty proxy
#result_proxy:
#    url : http://127.0.0.1:3000/
#    key : your_morty_proxy_key

outgoing: # communication with search engines
    request_timeout : 2.0 # seconds
    useragent_suffix : "" # suffix of searx_useragent, could contain informations like an email address to the administrator
    pool_connections : 100 # Number of different hosts
    pool_maxsize : 10 # Number of simultaneous requests by host
# uncomment below section if you want to use a proxy
# see http://docs.python-requests.org/en/latest/user/advanced/#proxies
# SOCKS proxies are also supported: see http://docs.python-requests.org/en/master/user/advanced/#socks
#    proxies :
#        http : http://127.0.0.1:8080
#        https: http://127.0.0.1:8080
# uncomment below section only if you have more than one network interface
# which can be the source of outgoing search requests
#    source_ips:
#        - 1.1.1.1
#        - 1.1.1.2
